apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: feedback-viewer
  name: feedback-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-viewer
  strategy: {}
  template:
    metadata:
      labels:
        app: feedback-viewer
    spec:
      containers:
      - image: tbsacr.azurecr.io/feedback-viewer:1.0.0
        imagePullPolicy: Always
        name: feedback-viewer
        resources: 
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 512Mi

