apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: feedback-viewer
  name: feedback-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-viewer
  template:
    metadata:
      labels:
        app: feedback-viewer
    spec:
      containers:
        - name: feedback-viewer
          image: tbsacr.azurecr.io/feedback-viewer:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: 12Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /health # The endpoint in your application that indicates it is healthy
              port: 8080
            initialDelaySeconds: 60 # Adjust based on your application startup time
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
